### ISSUE TITLE
Clarify Clear All popup.

### ISSUE THREAD

**Issue by revilowaldow** [jacobwojoski/dice-stats#111]
Please adjust the "Clear All" popup to include reference to the module.

Having "Clearing ALL Player Data (Local And DB). Are you sure?" popping up with no obvious context can be concerning for users.
This is trivially fixed by changing the string to say "Clearing ALL **Dice Stats** Player Data (Local And DB). Are you sure?"

**Comment by OxTailSafu** [comment]
If also possible, I would maybe suggest not having this on by default too. It caught me completely by surprise when I suddenly started getting this popup.

**Comment by jacobwojoski** [comment]
Updated in build 1.17.4
