### ISSUE TITLE
[System Request] Cyberpunk Red system compatibility

### ISSUE THREAD

**Issue by RonJomero** [jacobwojoski/dice-stats#118]
The system does print dice rolls to chat when rolled from character sheet stats, but it seems to do so in a way that isn't being picked up by the module.   Would love to see compatibility with this mod and that system.

**Comment by jacobwojoski** [comment]
I’ll take a look. Sometimes it’s a system issue though and will need to wait for them to update it.

**Comment by jacobwojoski** [comment]
System not supported for V12. lmk if it works fine in v12 and ill reopen the issue
