### ISSUE TITLE
[Bug] Hit Miss Tracker not working on Pathfinder 2e v5.15.3

### ISSUE THREAD

**Issue by SoupcanAnthill** [jacobwojoski/dice-stats#125]
Switching to that tab comes up with an error message saying "Feature not supported for your current system". Worked on 5.15.1, but has broken since then.

**Comment by jacobwojoski** [comment]
Does it work once you start making attacks? Some quick testing today seemed to have it not show up initially but once rolls started being tracked it worked.   

Will do some more investigating tomorrow.

**Comment by SoupcanAnthill** [comment]
Yes, you're right, it looks like once it has data it works correctly. I assumed it would backfill from the chat log, that's my mistake. Maybe switch the error message to say "not supported or no data"? Regardless, thank you!

**Comment by jacobwojoski** [comment]
Ah yeah none of the stats backfill. It’s pulls data whenever a chat msg gets created so won’t load in any old data that was already created.   

Will make a different display for each tab.
