### ISSUE TITLE
[Feature Request] Pause saving roll data

### ISSUE THREAD

**Issue by joonhohw** [jacobwojoski/dice-stats#130]
I keep my server/world up for my players during the week for testing and they usually end up doing test rolls and such.
Would it be possible to implement a feature similar to https://github.com/Yosoy-Ed/simple-d20-stats that allows for the GM to pause saving roll data?

**Comment by jacobwojoski** [comment]
Cool idea. I’ll see what I can do

**Comment by jacobwojoski** [comment]
Closes, Added in 1.19.0
