### ISSUE TITLE
New option: Include/Exclude Initiative Rolls

### ISSUE THREAD

**Issue by mbmerrill** [jacobwojoski/dice-stats#139]
I'd like to see an option to include/exclude initiative rolls from the stats.

**Comment by jacobwojoski** [comment]
For what system? This would need to be a system specific implementation.  

For D&D & PF2 there should be subcategories for D20 rolls under the D20 stats tab to see how each type of roll performed

**Comment by mbmerrill** [comment]
Oh, I didn't realize it was specific to the system.  I'm on pf1.

**Comment by jacobwojoski** [comment]
Yeah, every game system can implement initiative differently. 

Some systems I’ve added parsers for different d20 rolls. PF1 should have a D20 stats tab to see specific types of rolls. (You can enable/ disable tabs in settings so it might be disabled) or I might have messed something up in an update so if it’s enabled but not showing up lmk
