### ISSUE TITLE
Way to retroactively grab dice rolls from a non-deleted chat?

### ISSUE THREAD

**Issue by jrbuda** [jacobwojoski/dice-stats#18]
Each time I restart my Foundry app/world, I lose all dice stats. Is there a way to make that persistent or have it parse the chat on load?
If that is already in development, don't mind me then.
Thank you

**Comment by jacobwojoski** [comment]
The main design goal is to see stats of the session so it only tracks data if your in the game. Although this does mean if other player rolls were made before you were in the game you wont have them on your screen. 

- Current plan: I'm thinking I'll make it so if players leave and rejoin they will request rolls from the gm. But if the GM leaves they wont have a way to get the roll history. 
- A feature to export and import rolls from a file is planned.

- might add a db storage thing where the gm can save stats in the backend to the server which would be reloaded when rejoining but this is low pri for now as wasn't the main design goal of the module.

**Comment by jrbuda** [comment]
Ah gotcha, I misunderstood the scope of the project. I definitely think this module is still useful and I will continue using it. Thank you!

**Comment by jacobwojoski** [comment]
All good. Will try to make it more clear on the readme but ill look into adding a setting to allow saving stats between sessions. Shouldn't be too difficult.

**Comment by jacobwojoski** [comment]
Issue #19
