### ISSUE TITLE
[Feature] Load Stats if joining game late. Make Stats Persistent?

### ISSUE THREAD

**Issue by jacobwojoski** [jacobwojoski/dice-stats#19]
Create DB location for Dice Stats (Make Values persist between sessions?)
- When user joins game, ask GM to save data to DB. Then pull DB values
- Save to DB Button (GM only?)
- Setting to allow players to save to DB
- GM save to DB upon exit of game.

**Comment by brunocalado** [comment]
Persistent would be really nice!

**Comment by AKCarter07** [comment]
Awesome module!
Seconding the request for persistent stats. 
Long-term, storing with session date so stats can be pulled for date ranges as well would be really cool, but low priority.

**Comment by jacobwojoski** [comment]
> Awesome module! Seconding the request for persistent stats. Long-term, storing with session date so stats can be pulled for date ranges as well would be really cool, but low priority.

Don't know about implementing stats for time ranges. That would basically need a very in depth database that doesn't rly work for foundry. Working on persistent storage now though and plan to add an export feature so you can save the data locally and do whatever you want with it.

**Comment by ChiefMilesEdgeworth** [comment]
Big plus one on persistent stats, I really like how the data is presented in this module, but sometimes Foundry requires a reset to fix issues mid session, which can lead to lost data. I'd be happy to at least try to help, though I don't have a lots of experience working on Foundry modules in particular.

**Comment by jacobwojoski** [comment]
I have an idea planned should be done soon ish. Went a bit overboard trying to set up alot of automation but scaling back and instead just going to make it some buttons that users can press to save and load other players data for now. One that's done and if you want to look into it feel free!

**Comment by jacobwojoski** [comment]
Will prolly release the DB feature by the end of the week. Plz put any Issues for suggestions if desired!

**Comment by jacobwojoski** [comment]
Release Made. Submit any recommendations you may have while using it!
