### ISSUE TITLE
[Feature] Comparison Tool

### ISSUE THREAD

**Issue by jacobwojoski** [jacobwojoski/dice-stats#2]
Allow users to select multiple players and compare stats side by side. 
(Make player comparisons with just graphs and leave other stats out for now?)
(Different color bar lines on same graph vs put data side by side?)

**Comment by brunocalado** [comment]
> 

Tough. Maybe just allow to export to CSV would be easy. You paste on a spreadsheet and you get the Comparison.

**Comment by jacobwojoski** [comment]
Have a few Ideas. Prolly gonna make a special form for comparing players. But Low Pri for now
