### ISSUE TITLE
Math seems incorrect

### ISSUE THREAD

**Issue by jrbuda** [jacobwojoski/dice-stats#23]
![image](https://user-images.githubusercontent.com/47678481/221433395-4b79eff7-d60e-42a4-98e9-cb7d56dcff6e.png)
Median is showing as 20 and mode is showing as 2.

Fixes itself after some rolls are added but the streak data is hard to understand:
![image](https://user-images.githubusercontent.com/47678481/221433475-60acaea5-3e29-4ea5-9f66-554fb519373a.png)

**Comment by jacobwojoski** [comment]
Mode is working correctly. Currently only uses the first number. Duplicate modes aren’t displayed. Will be fixed in a future update. Will look into median. Prolly messed some math up somewhere

**Comment by jacobwojoski** [comment]
Mode not changed. Fixed median. Update to v1.4.1
