### ISSUE TITLE
Dice stats not capturing correctly

### ISSUE THREAD

**Issue by bryanoakley** [jacobwojoski/dice-stats#24]
![dice-stats-not-capturing](https://user-images.githubusercontent.com/62300992/221436629-de2b7701-c65a-47b8-9837-b3f8f34bb16e.PNG)

It appears that if you roll a bunch of different dice types together it doesn't correctly capture the data. We can see that I rolled just a random array of die which includes 4d6 and then later rolled 2d6 on it's own. The dice stats only include that 2d6. If this is intended I'd love an option in the future to include all rolls to be added to the roll data collection regardless of if it's combined with another roll or not.

**Comment by jacobwojoski** [comment]
Not intended, will investigate

**Comment by jacobwojoski** [comment]
Fixed in 1.5.0
