### ISSUE TITLE
[Bug] Conflict with Token Health mod

### ISSUE THREAD

**Issue by apoapostolov** [jacobwojoski/dice-stats#28]
When used with Token Health, the checkboxes in the Dice Stat window are always empty, do not get filled when clicked off/on

**Comment by jacobwojoski** [comment]
Can you link to the module? I think I have the Token Health Module (Unless I have a different one) and I believe it works for me. try pressing f12 and view console. See if there is an error/ linking a photo of the error would be a great help. 
Will investigate.

Photo example Issue #7

**Comment by apoapostolov** [comment]
Here you are: https://github.com/schlosrat/token-health

foundry.js:727 Foundry VTT | Error thrown in hooked function '' for hook 'renderApplication'
#call @ foundry.js:727
callAll @ foundry.js:681
_render @ foundry.js:5153
await in _render (async)
_render @ foundry.js:5822
render @ foundry.js:5067
_handleButtonClick @ dice-stats-main.js:471
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 TypeError: Error thrown in hooked function '' for hook 'renderApplication'. Cannot read properties of undefined (reading 'contains')
[Detected 1 package: pf2e-dorako-ui]
    at Object.fn (misc-hooks.js:107:25)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at PlayerStatusPage._render (foundry.js:5153:13)
    at async PlayerStatusPage._render (foundry.js:5822:5)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:728
callAll @ foundry.js:681
_render @ foundry.js:5153
await in _render (async)
_render @ foundry.js:5822
render @ foundry.js:5067
_handleButtonClick @ dice-stats-main.js:471
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:727 Foundry VTT | Error thrown in hooked function '' for hook 'renderApplication'
#call @ foundry.js:727
callAll @ foundry.js:681
_render @ foundry.js:5153
await in _render (async)
_render @ foundry.js:5822
render @ foundry.js:5067
_handleButtonClick @ dice-stats-main.js:471
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 TypeError: Error thrown in hooked function '' for hook 'renderApplication'. Cannot read properties of undefined (reading 'contains')
[Detected 1 package: pf2e-dorako-ui]
    at Object.fn (dark-theme-hooks.js:35:24)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at PlayerStatusPage._render (foundry.js:5153:13)
    at async PlayerStatusPage._render (foundry.js:5822:5)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:728
callAll @ foundry.js:681
_render @ foundry.js:5153
await in _render (async)
_render @ foundry.js:5822
render @ foundry.js:5067
_handleButtonClick @ dice-stats-main.js:471
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:727 Foundry VTT | Error thrown in hooked function '' for hook 'renderApplication'
#call @ foundry.js:727
callAll @ foundry.js:681
_render @ foundry.js:5153
await in _render (async)
_render @ foundry.js:5822
render @ foundry.js:5067
_handleButtonClick @ dice-stats-main.js:471
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 TypeError: Error thrown in hooked function '' for hook 'renderApplication'. Cannot read properties of undefined (reading 'contains')
[Detected 1 package: pf2e-dorako-ui]
    at Object.fn (base-theme-hooks.js:87:24)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at PlayerStatusPage._render (foundry.js:5153:13)
    at async PlayerStatusPage._render (foundry.js:5822:5)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:728
callAll @ foundry.js:681
_render @ foundry.js:5153
await in _render (async)
_render @ foundry.js:5822
render @ foundry.js:5067
_handleButtonClick @ dice-stats-main.js:471
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:727 Foundry VTT | Error thrown in hooked function '' for hook 'renderApplication'
#call @ foundry.js:727
callAll @ foundry.js:681
_render @ foundry.js:5153
await in _render (async)
_render @ foundry.js:5822
render @ foundry.js:5067
_handleButtonClick @ dice-stats-main.js:471
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:747 TypeError: Error thrown in hooked function '' for hook 'renderApplication'. Cannot read properties of undefined (reading 'contains')
[Detected 1 package: pf2e-dorako-ui]
    at Object.fn (base-theme-hooks.js:129:23)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at PlayerStatusPage._render (foundry.js:5153:13)
    at async PlayerStatusPage._render (foundry.js:5822:5)

**Comment by jacobwojoski** [comment]
Thanks for the extra info. 
Very strange issue but seems like its a problem with token health itself. 
I Made a blank form with just checkboxes and no other info and it was messed up for them to. 
Somereason their mod is messing with checkbox input types or something

**Comment by jacobwojoski** [comment]
Found the issue. Will be fixed in next release
