### ISSUE TITLE
[Bug] manifest problem

### ISSUE THREAD

**Issue by brunocalado** [jacobwojoski/dice-stats#33]
every time you update you got this:

![image](https://user-images.githubusercontent.com/4999783/225383081-c354d3dc-b6ac-4fff-92c8-197f99914d7f.png)

**Comment by jacobwojoski** [comment]
Will investigate. Prolly happened when I was trying to fix socketlib not allowing auto downloading

**Comment by jacobwojoski** [comment]
Should be fixed now

**Comment by jacobwojoski** [comment]
Missed updating a version number in the module.json should be good. 
Was tested and verified here but thats for letting me know!
