### ISSUE TITLE
[Feature] Another button to access the stats

### ISSUE THREAD

**Issue by jrbuda** [jacobwojoski/dice-stats#36]
I usually hide my player list so that I can have more screen space. Is it possible to get the stats buttons somewhere else or a hotkey or something?
Thank you

**Comment by jacobwojoski** [comment]
Planned feature for the future. Some other priories first though. 
Don't know best location yet but might come up with a partial solution now and improve upon it later

**Comment by jacobwojoski** [comment]
Next release will have setting to choose another button to access values. Optional access button will be moved to the Scene control area (Tokens, effects, measure, ect). Looking into allowing users to change players ions from everyone being the D20. Will Probably be limited to free font awesome Icons + any Foundry specific icons [View Icons Link](https://fontawesome.com/search?m=free&o=r)

**Comment by jacobwojoski** [comment]
Feature Added. Give it a Shot and let me know if you find anything wrong. In the Process of adding better instructions to the readme on how to make custom icons for the players
