### ISSUE TITLE
dice stats is colliding with token mirror button

### ISSUE THREAD

**Issue by GamepadRanger** [jacobwojoski/dice-stats#60]
When both dice stats and [token mirror button](https://github.com/MAClavell/Token-Mirror-Button/) are installed and activated, dice stats is working, but token mirror button will be prohibited from loading and will not function at all.

![2023-05-21_00h03_42](https://github.com/jacobwojoski/dice-stats/assets/98288004/79cf8729-f6f6-4180-88ea-e95895fb8c5b)

As soon as I disable dice stats, the other module works as inteded again.

Foundry version 10 / Build 291
Dice Stats version 1.10.0 and 1.11.0
Token Mirror Button version 1.4.0

I'm not sure why it is behaving like this, but after disabling all modules and then enabling them one by one, Dice Stats seems to be the one that clashes with Token Mirror Button (or vice versa).

**Comment by jacobwojoski** [comment]
Looks like a collision with my global value being the same as someone else. 
Latest release (1.11.1) Should fix it. Going to close the issue but if its still broken lmk
