### ISSUE TITLE
[system request] Expand the compatibility with Pathfinder 1e

### ISSUE THREAD

**Issue by Sp33dfire** [jacobwojoski/dice-stats#61]
Currently, the roll data from attacks are not counted. I assume that's due to the way that the attack cards for attacks are made up. Saves and other dice rolls made directly from the character sheet and manually rolled dice are counted though.

**Comment by jacobwojoski** [comment]
Will take a look. The mod works by pulling a value from the chat called ROLLS that’s built into foundry by default. So depending how pf1e does it. I might close and make an issue on their GitHub.

**Comment by jacobwojoski** [comment]
PF1 Roll OBJ, Reference for what I need to parse

![image](https://github.com/jacobwojoski/dice-stats/assets/124112219/0b307461-9448-4bbd-aa3b-89bd7a3f594f)

**Comment by Sp33dfire** [comment]
Cards can hold buttons for rolling saves, though you can always roll any dice directly from your character sheet.
For the record, I'm currently on Build 315 V 11 with Pathfinder being on 9.6 and Dice Stats on 1.15.0. Currently there are no dice rolls being recorded, regardles if they're done via sheet, card or directly in chat.

**Comment by jacobwojoski** [comment]
Dice stats is up to 1.17 now so might fix some of the problems. I have a potential fix for pf1 in the works. Just in testing rn. I’ll ping this when it’s out

**Comment by jacobwojoski** [comment]
@Sp33dfire 1.17.5 Should now track Attack, Damage, and Crit Confirm rolls

**Comment by Sp33dfire** [comment]
Thank you very much! I just checked it and it seems it tracks every kind of rolls now. Including saves from cards, direct chat rolls and like all the rolls from the character sheets.
