### ISSUE TITLE
[Question/Enhancement] Why are the all the data stored in flags instead of an external data structure like .json

### ISSUE THREAD

**Issue by MichalGolaszewski** [jacobwojoski/dice-stats#62]
Won't this approach cause all the roll data to be presistently loaded together with the users causing an overall drop in performance the more data is stored? Especially that it bloats with evert session?
On the Foundry wiki the answer for storing data of that kind seems to be an external data storage like .json. I've seen few other modules do that. (eg. `DF Chat Enhancements` does exactly that to lighten the load of the session and creates a .json-based archive of chat history)

It would be nice if the archived data was loaded only when the statistics screen is being opened.

**Comment by MichalGolaszewski** [comment]
Oh, that's a clever way to store the roll info, I like it :D
I was worried that you'd register the results themselves in an ever-grownig array/archive. (Only had took a glance at the module so far.) So I was worried about the performance impact of having that loaded up in the cache at all times even if player is not looking at the stat analysis, because my players already start to complain about the performance of our session.

Now that you explained it I'm relived. Seems like the module is a lot more lightweight than I expected even if it's all kept in flags at all times :) 

Thanks for the work and godspeed to you :D

**Comment by jacobwojoski** [comment]
Original design of the mod that I forked had an every growing list and wanted a way to avoid that. Especially when needing to do math on these giant arrays. 

Glad you like it and may your averages be above average XD! 
Also Take a look at the Usage->Icons section of the **readme** to update some of your players icons if you haven't yet!
