### ISSUE TITLE
[System Request] SWADE

### ISSUE THREAD

**Issue by brunocalado** [jacobwojoski/dice-stats#7]
Great module!

Can you make it work for SWADE?

**Comment by jacobwojoski** [comment]
Will need to see how rolls are done In those systems. As long as it posts rolls to a central area it should be easy enough. If roll data isn’t global then it would be a lot harder

**Comment by brunocalado** [comment]
Thank you.

But, SWADE has a exploding die feature.

If you roll the max number on a die, you roll again and sum up.
![image](https://user-images.githubusercontent.com/4999783/219984170-708d2175-0333-45f3-92c6-2c7491d44bcc.png)

Is it possible to take this in account?

**Comment by jacobwojoski** [comment]
Possible but need to learn and look into how to check what system is being run. Then change how chat dice parsing works. Looking into the system the exploding dice are not part of the Chat message ROLLS[ ] data and instead are a special custom field. Will take a bit.

**Comment by jacobwojoski** [comment]
Give it a shot now and see if this works New update in 1.5.0 might have fixed it.

**Comment by brunocalado** [comment]
> Give it a shot now and see if this works New update in 1.5.0 might have fixed it.
> 
> Should have fixed it

Thankyou, but I can't see the exploding dice. Also, there is an error when I click refresh
![image](https://user-images.githubusercontent.com/4999783/221450098-c4624ffd-b091-4727-a6ba-c74f5183a370.png)

**Comment by jacobwojoski** [comment]
Any  chance you could disable all other mods (Other then socket lib) and try it. And if it does a list of mods would be nice. Testing locally it seems to work fine on my end. The error seems to be coming from a "cleaner-sheet-title-bar.js" file which I cant find anywhere so I think it might be another module causing issues.

**Comment by jacobwojoski** [comment]
might have found it. looks like its the cleaner-title-bar module. but dont know for sure. Id see if you can disable it and see if it works. Wondering if its the only thing causing issues

**Comment by jacobwojoski** [comment]
Tried installing cleaner sheet title bar and didn't get the error. Think it might be an interaction with another mod. lmk if disabling mods fix it and getting a list of mods would help solve the problem

**Comment by brunocalado** [comment]
> Referen

It's **cleaner sheet title bar** fault. What can be done about it?
![image](https://user-images.githubusercontent.com/4999783/221579226-f1cbc133-8e2b-4888-b594-cb39e854c9ec.png)


Identify the exploding event is hard to add?

**Comment by jacobwojoski** [comment]
Does it get the exploding die info if cleaner sheet is disabled? Because on my end it appears to record the exploding dice fine. It auto rolls the exploding die for me so idk if you might have a different setting where you manual reroll the exploding die values?

I can look into adding support for cleaner-sheet-title-bar to fix the error.

**Comment by brunocalado** [comment]
> 

Yes. I disabled cleaner mod

I can't see the exploding dice
![image](https://user-images.githubusercontent.com/4999783/221582856-ab132d01-369f-4996-95cc-d66ce8b967e1.png)

**Comment by jacobwojoski** [comment]
Will need to investigate. Maybe I don't fully understand exploding dice feature. Will take a photo later to show what I see on my end. In your photo are both 9's made up of more then 1 dice roll? If both are made up of a 6 & a 3 it appears to work? As that would have made 6 3's rolled and you have 6 rolls counted.

**Comment by brunocalado** [comment]
> 

SWADE dice rolling works like that:

There are two types of actors: Wild Card and Extra
**Wild Card** You roll the Wild Die and the Trait Die. You pick the better roll from them.

**Extra** You roll the Trait Die.

**Trait** a skill is a trait

**Roll Example**
**Wild Card** Skill Notice D8
The player roll D8 and D6 (wild die)
**Case 1**
D8: 6 and D6: 6 and 5 = total 11
**Case 2**
D8: 8 and 7 and D6: 4  = total 15
**Case 3**
D8: 1 and D6: 1 = total 1 - critical failure
**Case 4**
D8: 8 and 8 and 8 and 3 and D6: 3 = total 27

**Comment by FloRad** [comment]
Hi Jacob, I'm the swade system developer! If you have any technical questions about how the system rolls etc work then please feel free to hit me up on Discord! Just ping me in the #swade channel on the FoundryVTT discord and I'll be happy to help you out.

**Comment by jacobwojoski** [comment]
![image](https://user-images.githubusercontent.com/124112219/221712130-cff129c0-fa81-4fae-9a14-1e23f4943ffd.png)

It looks like it works here for me unless the issue is not with Skills? Made 2 skill checks. Second rolled a 6 on the wild die. 3d6 and 2d4 rolled and dice stats says that.

**Comment by jacobwojoski** [comment]
Exploding d4's seems fine to me too. 
![image](https://user-images.githubusercontent.com/124112219/221712843-4acef076-5982-45f0-b925-55d71cc20022.png)

**Comment by jacobwojoski** [comment]
Streak looks fine to me. 
Streaks are when the player rolled and got results in an incrementing order. Ex: 5,6,7,8 or 15,16,17,18,19,20
You rolled the following:
D4 rolls: 2,2,3,4,3 -> Streak of 2,3,4
d6 rolls: 2, 6, 3, 3, 3 -> longest streak of 1 so nothing is displayed. Only when streaks reach 2+ values it gets displayed

**Comment by brunocalado** [comment]
> 

Oh. I understood. 

I thought the streak would be used for the exploding dice. So, You rolled 6 and 3, your streak is 6,3.

But, it's great! Thank you

**Comment by jacobwojoski** [comment]
Working for SWADE
