### ISSUE TITLE
[BUG] Setting "see GM roll data" and "see GM stats in global roll data" not working

### ISSUE THREAD

**Issue by ZeroXNoxus** [jacobwojoski/dice-stats#75]
I've disabled both so players can't see my dice rolls via the dice chart as we play without revealing the actual roll from the DM (gives me the ability to fudge dice sometimes to not kill a player, not reveal hit modifiers etc.)

Sadly, even when rolling with private GM rolls, the chart gets updated with the roll of the GM and the players can see this on the chart. I'd highly appreciate this being fix ASAP.

**Comment by jacobwojoski** [comment]
Are you using it on PF2e or another system?

**Comment by jacobwojoski** [comment]
new Release out
