### ISSUE TITLE
[Bug] Database operations fail

### ISSUE THREAD

**Issue by Hertzila** [jacobwojoski/dice-stats#77]
Hello.

It seems like there's a bug whenever the module attempts to load its roll database. Both on the ready hook and manually attempting to load causes it to error out with a ```dice-stats-db.js:120 Uncaught (in promise) TypeError: dbDieDataObj.MEANS is not iterable
    at DB_INTERACTION.createPlayerObject (dice-stats-db.js:120:62)``` error message in the console.

The world has previously had plenty of modules, but the same thing happens even if I turn all of them off. Log from the clean start: 
[localhost-1692580133887.txt](https://github.com/jacobwojoski/dice-stats/files/12390134/localhost-1692580133887.txt)

Otherwise the module *seems* to work normally. Any rolls in the chat log are logged and show up in statistics normally.

**Comment by jacobwojoski** [comment]
Yeah been looking into it but its a bit finkey trying to debug. Seems like all the features still work fine Including the MEANS. 

You can clear the warning by pressing "CLEAR ALL DATA" on the global stats page as the GM. But you will loose you history of tracked rolls.

**Comment by jacobwojoski** [comment]
Let me know if this isnt fixed. Latest update should have fixed problem. If you wipe your database though it will fix it and you wont get the error anymore. I cant recreate the problem on my end now that I did that but I put in something I think fixed it

**Comment by Hertzila** [comment]
Gotcha. After clearing the database, it seems to work fine, no errors after a session and things seem to record properly. I'll keep looking if it errors out, but so far so good.
