### ISSUE TITLE
module.json in 1.14.4 zip still has a 1.14.3 version number.

### ISSUE THREAD

**Issue by tehguitarist** [jacobwojoski/dice-stats#86]
Title says it all really. The loose module.json is all good, it's just the zipped one.

No issues with the module itself, just keeps trying to update when "Update All" is selected in foundry, so nothing major.

**Comment by jacobwojoski** [comment]
Should be fixed. Version 1.15.0 now available.

Must of forgot to push the version number file change.... oops lol.
