### ISSUE TITLE
[SUGGESTION] Support for midi-qol merged chat card

### ISSUE THREAD

**Issue by 9ryex5** [jacobwojoski/dice-stats#9]
Many people use [Midi-qol](https://foundryvtt.com/packages/midi-qol) to automate dnd5e, however Dice Stats can't pick on rolls if "Merge Rolls to one card" setting is enabled (it probably uses a different workflow to make rolls).
![image](https://user-images.githubusercontent.com/43207603/219814967-4f520952-b254-447f-bbf2-ed48f8b4ed51.png)

[Midi-qol](https://foundryvtt.com/packages/midi-qol) has some [hooks](https://gitlab.com/tposney/midi-qol#midi-qol-called-hooks) when it makes rolls, so I think it's possible to get rolls from it.

It also has a [statistics](https://gitlab.com/tposney/midi-qol#roll-statistics) feature, so this might help.

**Comment by jacobwojoski** [comment]
Don't know of an easy way to do this. As far as I know there's no "OnChatMessageChange" Hook. Ill look closer into the Midi-Qol stuff to see but the easiest way would be if they add one. Otherwise It would prolly be really difficult.

**Comment by 9ryex5** [comment]
There is a very active Midi-qol [thread](https://discord.com/channels/170995199584108546/1010273821401555087) on Foundry Discord, i'm sure they will know what to do there.

**Comment by jacobwojoski** [comment]
![image](https://user-images.githubusercontent.com/124112219/219835632-cea23f5d-643a-42cd-bc42-3c62335fc929.png)
Saving Info here incase I forget. Looks like its relatively easy to to using this data. Will need some extensive testing to see if it works for saving throws and non d20 dice.

**Comment by jacobwojoski** [comment]
Is this only an issue for dmg after attack rolls? Testing locally it appears saves & dmg from spell attacks make new cards so it should save correctly.

**Comment by jacobwojoski** [comment]
Okay I can do most of the fix. Would need some testing done to see if it fully works. Working through the last issue now. Need a way to be able to get the player id if the player that "owns" the midi-qol roll and it should work

**Comment by 9ryex5** [comment]
> Is this only an issue for dmg after attack rolls? Testing locally it appears saves & dmg from spell attacks make new cards so it should save correctly.
> 
> Edit. Looks like saving throws are fine but the dmg roll from the spell doesnt save correctly?

For attacks, attack rolls and damage don't work because they are merged into one card.
For spells, damage doesn't work (is merged). Saving throws work because it's a new card

**Comment by jacobwojoski** [comment]
Have a fix that should work ready to merge it. Only issue is there's not an easy way to see what player made the roll only what character did. 

I made it so the player that owns the character that made the roll gets credit for the roll. Although this means if all players own every player character it wont work. As well as if the GM rolls a character roll the player will get credit instead of the gm.

**Comment by jacobwojoski** [comment]
Merged. Tell me what you think so I can close issue. Check incompatibilities to see the possible issues with it still.

**Comment by 9ryex5** [comment]
> Have a fix that should work ready to merge it. Only issue is there's not an easy way to see what player made the roll only what character did. This is a problem with midi-qol and asking around on discord couldn't solve the issue. midi doesn't pass the Player who pressed the button. It shows only what character the roll was associated with.
> 
> I made it so the player that owns the character that made the roll gets credit for the roll. Although this means if all players own every player character it wont work. It will only give credit to the last person to get ownership. Also, if the GM rolls for a player character the player will get credit instead of the GM.

I don't think many DMs make their players own each others characters, I certainly don't, it shouldn't be a problem. About the player getting credit for the GM roll, after pondering about it, I actually prefer it this way. I look at statistics as a character's "luck" so it makes sense for the player to take credit.

Thank you very much for the enhancement. Will have a session soon, but afterwards I'll test everything and report back :)

**Comment by 9ryex5** [comment]
Made a quick test, it seems not to pick non d20 dice for damage.
![image](https://user-images.githubusercontent.com/43207603/219969800-3c536226-da06-4ad8-af35-8371c9d686b0.png)

**Comment by jacobwojoski** [comment]
Copy pasted something wrong. Updating now

**Comment by jacobwojoski** [comment]
New release is out. Give it a shot now

**Comment by jacobwojoski** [comment]
Fixed Rolling multiple dice not working

**Comment by 9ryex5** [comment]
All seems to be working now
