### ISSUE TITLE
No player stats after updating

### ISSUE THREAD

**Issue by karpiq24** [jacobwojoski/dice-stats#97]
After updating from 1.15.1 to 1.16.1 players stats seem to reset for me and start tracking from a blank state. After downgrading this module the old stats are there again. GM (my) stats are correctly displayed in new version. Is there some migration process for this update?

**Comment by jacobwojoski** [comment]
Unfortunately probably not. I Added the tracking of ability rolls to player stats so it messed with the Database in the process. (Personally I use the mod as per session stats and clear it every game)  

Need to better improve the database to handle updates like this in the future though.

**Comment by karpiq24** [comment]
I understand that it would be impossible to correctly assign previous rolls to specific categories. I don't understand why GM rolls all are still visible as unknown rolls and I still can see other dice rolls stats and charts. Only player stats disappeared (all dice stats - not only d20).

Data is still there because when I downgrade this module all stats return to normal.

**Comment by jacobwojoski** [comment]
It’s hard for me to test from not being able to recreate the issue easily.   

I think it had to do with the update making the Players info and the DB being mismatched. So, when it tries loading old DB values in to the players data it can’t parse the DB info correctly and marks them all as unassigned / undefined behavior. 

I have a bug to change how I implemented the DB so I’ll get to it eventually and should fix most these issues.  

But for the time being any updates to the DB will break current builds usually require a clearing of all data to fix.

**Comment by jacobwojoski** [comment]
Might have found a potential fix without a full DB rewrite. Update should be out tomorrow afternoon.

**Comment by jacobwojoski** [comment]
Possible fix just released in 1.17.2

Let me know if it doesnt work and ill reopen the issue

**Comment by karpiq24** [comment]
Old stats show up correctly in All Dice Stats tab.

There are some issues in D-20 tab:
* charts only show new rolls (and do not load at all if there are no new rolls since update)
* Old total dice rolled shows up in Ability Rolls instead of Unknown Rolls but Avg shows up in unknown

![obraz](https://github.com/jacobwojoski/dice-stats/assets/14124267/21856d10-c4c2-4319-a495-68b38c9acf3b)

**Comment by jacobwojoski** [comment]
Aight. I’ll look into it more

**Comment by jacobwojoski** [comment]
Okay Fix Part 2 Is Live.

 Give it a shot. If not it will prob need to wait for a DB overhaul or the import/export feature

**Comment by karpiq24** [comment]
Still same issue in D-20 tab. I might just clear the stats, I'm not that attached to them.
I don't know if its worth your effort if its only me complaining :smiling_face_with_tear:

**Comment by jacobwojoski** [comment]
I’ve definitely seen the issue and thought I knew how to fix it. Problem is once i clear the db I can’t recreate the problem so it’s a bit tough to test lol. Once you clear the stats it should work.  

Last thing if you want I’d suggest press f12 before you join the game and if you get any errors on the console tab when joining sake a snip and paste it here.

**Comment by karpiq24** [comment]
There are no erros when joining a game but one appears when I open players stats:
```
Uncaught SyntaxError: expected expression, got '>'
[Detected 3 packages: dice-stats, monks-wall-enhancement, lib-wrapper]
    jQuery 3
    _injectHTML foundry.js:6012
    _render foundry.js:5835
    _render foundry.js:6532
    render foundry.js:5769
    onClick dice-stats-scenecontrol.js:94
    _onClickTool foundry.js:77766
    _onClickTool monks-wall-enhancement.js:266
    jQuery 9
    activateListeners foundry.js:77721
    _render foundry.js:5842
    render foundry.js:5769
    initialize foundry.js:77672
    activate foundry.js:35016
    _onClickLayer foundry.js:77740
    _onClickLayer Bundle.js:70249
    jQuery 9
    activateListeners foundry.js:77720
    _render foundry.js:5842
    render foundry.js:5769
    initialize foundry.js:77672
    _handleConfigUpdate Bundle.js:70286
    init Bundle.js:70269
    handleReady Bundle.js:129372
    async* Bundle.js:129406
    #call foundry.js:730
    callAll foundry.js:687
    setupGame foundry.js:8746
    _initializeGameView foundry.js:9990
    _initializeView foundry.js:9966
    initialize foundry.js:8650
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:805
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:91833
    async* foundry.js:91809
game:273:41
```
And one more after switching to D-20 stats tab:
```
Uncaught SyntaxError: expected expression, got '>'
[Detected 2 packages: dice-stats, monks-wall-enhancement]
    jQuery 6
    _replaceHTML https://[redacted_domain]/scripts/foundry.js:5991
    _render https://[redacted_domain]/scripts/foundry.js:5822
    _render https://[redacted_domain]/scripts/foundry.js:6532
    render https://[redacted_domain]/scripts/foundry.js:5769
    _handleButtonClick https://[redacted_domain]/modules/dice-stats/scripts/forms/dice-stats-tabedplayerstatspage.js:126
    jQuery 8
    activateListeners https://[redacted_domain]/modules/dice-stats/scripts/forms/dice-stats-tabedplayerstatspage.js:321
    _render https://[redacted_domain]/scripts/foundry.js:5842
    _render https://[redacted_domain]/scripts/foundry.js:6532
    render https://[redacted_domain]/scripts/foundry.js:5769
    onClick https://[redacted_domain]/modules/dice-stats/scripts/forms/dice-stats-scenecontrol.js:94
    _onClickTool https://[redacted_domain]/scripts/foundry.js:77766
    _onClickTool https://[redacted_domain]/modules/monks-wall-enhancement/monks-wall-enhancement.js:266
    jQuery 9
    activateListeners https://[redacted_domain]/scripts/foundry.js:77721
    _render https://[redacted_domain]/scripts/foundry.js:5842
    render https://[redacted_domain]/scripts/foundry.js:5769
    initialize https://[redacted_domain]/scripts/foundry.js:77672
    activate https://[redacted_domain]/scripts/foundry.js:35016
    _onClickLayer https://[redacted_domain]/scripts/foundry.js:77740
    jQuery 8
game:273:41
```

**Comment by jacobwojoski** [comment]
Okay so that bug was really weird. Its Failing to load the HTML Template but the template should be fine. 
I Fixed it by doing the following and have never seen the problem again:

1.) Delete the following line from the shown file but save the text somewhere. 
![image](https://github.com/jacobwojoski/dice-stats/assets/124112219/d5c3d86a-fd74-4e5c-a6ce-dc1cc99a881e)
 
2.) Launch back into the game and open the player stats. 
3.) Try Clicking the D20 Specifics Page  (Nothing should come up)
4.) Close the server
5.) Paste the text back in
6.) Launch again and it worked for me. 

Clearing the stats / uninstalling and reinstalling the module should also work. Other than that I cant find any reason why thats broken or any info about it so dont know how to fix it.

**Comment by karpiq24** [comment]
No issues after clearing stats.
